# Generated by Django 3.2.5 on 2022-07-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageslider',
            old_name='ImgPub_date',
            new_name='ImgagePub_date',
        ),
        migrations.RenameField(
            model_name='imageslider',
            old_name='Img_Desc',
            new_name='Imgage_Desc',
        ),
        migrations.RenameField(
            model_name='imageslider',
            old_name='Img_Name',
            new_name='Imgage_Name',
        ),
        migrations.AddField(
            model_name='imageslider',
            name='Imgage',
            field=models.ImageField(default='', upload_to='ksc/images'),
        ),
    ]
