# Generated by Django 4.0.6 on 2022-07-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksc', '0003_auto_20220714_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default='')),
                ('img', models.ImageField(default='', upload_to='ksc/images/slider')),
            ],
        ),
    ]
