# Generated by Django 4.0.6 on 2022-07-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksc', '0004_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='img',
            field=models.ImageField(default='', upload_to='ksc/images'),
        ),
    ]
