# Generated by Django 4.0.6 on 2022-07-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksc', '0007_member_alter_slider_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='memberName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='memberPosition',
            field=models.CharField(default='', max_length=50),
        ),
    ]
