# Generated by Django 4.0.6 on 2022-07-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksc', '0008_alter_member_membername_alter_member_memberposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgGall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgName', models.CharField(max_length=50)),
                ('altTxt', models.CharField(max_length=50)),
                ('gallImg', models.ImageField(upload_to='ksc/gallery')),
            ],
        ),
    ]
