# Generated by Django 3.0.5 on 2022-08-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksc', '0013_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='ksc/postImage'),
        ),
    ]
