# Generated by Django 3.0.5 on 2022-08-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksc', '0014_post_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Enter Person Name here', max_length=80)),
                ('title', models.CharField(default="Enter Person's Postion/working Area", max_length=80)),
                ('desc', models.CharField(default='Enter desc of person', max_length=1000)),
                ('img', models.ImageField(default='', upload_to='ksc/testimonialsImage')),
            ],
        ),
    ]
