# Generated by Django 3.0.5 on 2022-08-11 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksc', '0015_testimonials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonials',
            new_name='Testimonial',
        ),
    ]
