# Generated by Django 3.0.5 on 2022-08-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksc', '0016_auto_20220811_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventPost',
            fields=[
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(default='Enter Event Name here', max_length=80)),
                ('eventCategory', models.CharField(default='Enter Event Category here', max_length=50)),
                ('eventH1', models.CharField(default='Enter Event Heading1 here', max_length=80)),
                ('eventDesc1', models.TextField(default='Enter Event Description here', max_length=2000)),
                ('eventH2', models.CharField(default='', max_length=80)),
                ('eventDesc2', models.TextField(default='', max_length=2000)),
                ('eventH3', models.CharField(default='', max_length=80)),
                ('eventDesc3', models.TextField(default='', max_length=2000)),
                ('eventDateFrom', models.DateField(default='')),
                ('eventDateTo', models.DateField(default='')),
                ('eventImg1', models.ImageField(default='', upload_to='ksc/eventImages')),
                ('eventImg2', models.ImageField(default='', upload_to='ksc/eventImages')),
                ('eventImg3', models.ImageField(default='', upload_to='ksc/eventImages')),
            ],
        ),
    ]
