# Generated by Django 3.0.5 on 2022-08-16 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksc', '0017_eventpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='blogPost',
        ),
    ]
