# Generated by Django 3.0.5 on 2022-08-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksc', '0020_eventpost_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blogPostDesc1',
            field=models.TextField(default='Enter Event Description here', max_length=2000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blogPostDesc2',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blogPostDesc3',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blogPostH1',
            field=models.CharField(default='Enter Event Heading1 here', max_length=80),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blogPostH2',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blogPostH3',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blogPostImg1',
            field=models.ImageField(default='', upload_to='ksc/eventImages'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blogPostImg2',
            field=models.ImageField(default='', upload_to='ksc/eventImages'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blogPostImg3',
            field=models.ImageField(default='', upload_to='ksc/eventImages'),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='slug',
            field=models.CharField(max_length=130, unique=True),
        ),
    ]
