# Generated by Django 4.1 on 2022-09-06 04:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksc', '0023_blogpost_content_alter_contact_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='blogPostDesc1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='blogPostDesc2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='blogPostDesc3',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='blogPostH2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='blogPostH3',
        ),
        migrations.RemoveField(
            model_name='eventpost',
            name='eventDesc1',
        ),
        migrations.RemoveField(
            model_name='eventpost',
            name='eventDesc2',
        ),
        migrations.RemoveField(
            model_name='eventpost',
            name='eventDesc3',
        ),
        migrations.RemoveField(
            model_name='eventpost',
            name='eventH2',
        ),
        migrations.RemoveField(
            model_name='eventpost',
            name='eventH3',
        ),
        migrations.AddField(
            model_name='eventpost',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
