# Generated by Django 4.1 on 2022-09-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksc', '0025_eventpost_event_post_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpost',
            name='eventH1',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog_post_desc',
            field=models.CharField(default="Blog Post's Desc only show in Blog page, It does not shown in Blog post View page", max_length=1000),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='event_post_desc',
            field=models.TextField(default='Event Post Desc only for Event page, It does not shown in Event View page', max_length=1000),
        ),
    ]
