# Generated by Django 4.1 on 2022-09-06 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksc', '0026_remove_eventpost_eventh1_blogpost_blog_post_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='blogPostH1',
            new_name='blogPostName',
        ),
    ]
