# Generated by Django 4.1 on 2022-09-16 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksc', '0029_remove_blogpost_blogpostimg1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
